export const ENTRY_PROGRESS = 'ENTRY_PROGRESS';

export const SAVING_REQUEST = 'SAVING_REQUEST';
export const SAVING_SUCCESS = 'SAVING_SUCCESS';
export const SAVING_FAILURE = 'SAVING_FAILURE';

export const LOADING_REQUEST = 'LOADING_REQUEST';
export const LOADING_SUCCESS = 'LOADING_SUCCESS';
export const LOADING_FAILURE = 'LOADING_FAILURE';
